kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /tmp/data/db/
        containerPath: /tmp/data/db/
    extraPortMappings:
      - containerPort: 5000
        hostPort: 5000
        listenAddress: "0.0.0.0"
        protocol: tcp
